### PR TITLE
Better toString

### PR DESCRIPTION
**Pull request by Voltir**
Uses sourcecode.Name to add name to .toString methods of Rx.Dynamic and Rx.Var

### CODE REVIEW

**Comment by lihaoyi** [comment]
woohoo

**Comment by Voltir** [comment]
Nothing seems to explode in my larger project - anything else we want to do for 0.3.2?

**Comment by lihaoyi** [comment]
nope, i can run a release in two weeks when im back to a computer again

**Comment by Voltir** [comment]
@fdietze im contemplating bringing this up to date with 0.4.0, any thoughts?

**Comment by Voltir** [comment]
Closed in favor of #103

**Pull request closed without merging**
