### PR TITLE
Fixed leaky obs problem

### PR DESCRIPTION
**Pull request by Voltir**
Doh! Obs leaked..

Also bumps scala.js version to 0.6.6 and version to 0.3.1.-SNAPSHOT.

### CODE REVIEW

**Comment by pfn** [comment]
In addition to this, I'd like to see an explicitly managed version come back, i.e. restore Obs.apply; so that one can either do `val obs = Obs(rx) { ... }; ... obs.kill();` or `rx.trigger(...) // with automatic owner management`

**Comment by Voltir** [comment]
I don't think the async tests are very reliable.

**Comment by lihaoyi** [comment]
They're not lol

**Comment by Voltir** [comment]
I just commented out the problematic tests for the time being - I think this PR is good to go.

**Pull request merged**
