### PR TITLE
Activate multiset Zoomed Var test

### PR DESCRIPTION
**Pull request by fdietze**
I don't understand why this test is failing... Any ideas?

### CODE REVIEW

**Comment by Voltir** [comment]
It looks like an issue with how Zoomed special cases its `update()` method vs the generic handling of Var.set - I almost made it work with the following edits:
```
[info] @@ -152,8 +152,10 @@ object Var {
[info]      // Proxy Rx
[info]      override def now: S = rx.now
[info]  
[info] -    override private[rx] val downStream = rx.downStream
[info] -    override private[rx] val observers = rx.observers
[info] +    //override private[rx] val downStream = rx.downStream
[info] +    override private[rx] val downStream = rx.downStream ++ (base.downStream - rx)
[info] +    //override private[rx] val observers = rx.observers
[info] +    override private[rx] val observers = rx.observers ++ base.observers
[info]  
[info]      // Porxy Var
[info]      override def update(newValue: S): Unit = {
[info] @@ -162,8 +164,8 @@ object Var {
[info]        // avoid triggering rx, because we already
[info]        // know the current value: newValue
[info]        Rx.doRecalc(
[info] -        rx.downStream ++ (base.downStream - rx),
[info] -        rx.observers ++ base.observers
[info] +        downStream, //rx.downStream ++ (base.downStream - rx),
[info] +        observers //rx.observers ++ base.observers
[info]        )
[info]      }
```
But that change broke another test

**Comment by Voltir** [comment]
LoL. I am bad at git, but I did fix the test  ¯\_(ツ)_/¯

**Comment by fdietze** [comment]
Very nice fix!

> I am bad at git

You're probably not 😉. I made the history flat again by pulling the latest master, switching to this branch and run `git rebase master`. You seemed to have merged in the latest master to bring this PR up to date. Instead you can do `git rebase master` to bring branches up to date. This applies their changes from the previous master on top of the current master branch.

**Comment by Voltir** [comment]
I had originally rebased but when I went to push,  git complained my history had diverged - after which I did a pull, but perhaps I needed to do a pull --rebase? Or do I force push at that point?

**Comment by fdietze** [comment]
> I had originally rebased but when I went to push, git complained my history had diverged - after which I did a pull, but perhaps I needed to do a pull --rebase? Or do I force push at that point?

`git pull` is actually `git fetch; git merge origin/master`. This produces most unwanted merge commits. So yes, `git pull --rebase` is the correct command to use.

It is helpful to put this in your `.gitconfig`:
```ini
[pull]
    ff = only
rebase = true

[rebase]
autoStash = true
```

**Pull request merged**
